motd: 'Hello duckie, some random infos: 

- You can use the red or green dots below for disabling/enabling DJ changes notifications

- This website: <a href="https://sisyduck.com">sisyduck.com</A> can work offline in Hammahalle

- Please share the bot using this <a href="https://t.me/share/url?url=https%3A%2F%2Ft.me%2FbigSisyBot&text=Check%20out%20this%20cool%20bot%3A%20%40bigSisyBot">link</A> 

- You can pin the bot for easy access (similar to saved messages)

- There is a another bot running for festival lineups there: @shallowBunnyBot

- The source code is now available <a href="https://github.com/shallowBunny/app/">there</A>

Have fun! ğŸ˜˜' 


meta:
 nowShowShallowBunnyAd: false
 nowShowDataSourceAd: true
 nowShowSisyDuckAd: false
 nowTextAfterMap: ""
 nowShowPleaseSendData: false
 nowTextWhenFinished: 'Next party:Friday'
 nowBotUrl: "https://t.me/bigSisyBot"
 aboutBigIcon: "duck-192x192.png"
 aboutShowShallowBunnyIcon: true
 aboutShowSisyDuckIcon: false
 nowMapImage: ""
 roomYouAreHereEmoticon: "ğŸ¦†"
 mobileAppName: "BigSisyDuck"
 prefix: "duck"
 title: "Sisyphos"

beg: "Fri Aug 2 2024"
nbDaysForInput: 4
buttons: ["Now", "ALL", "Help"]
input: true
nowSkipClosed: false

rooms: ["ğŸ”¨ Hammahalle", "ğŸ’ƒğŸ•º Wintergarten", "â›´ Dampfer", "ğŸ–ï¸ Strand", "ğŸ¥¡ Tunnel"]

ğŸ¥¡ Tunnel:
- "1 16:00 120 0 Erley"
- "1 18:00 60 0 Rati *LIVE*"
- "1 19:00 60 0 3 A M"
- "1 20:00 60 0 4 A M"
- "1 21:00 60 0 5 A M"
- "2 16:00 180 0 Silent G"
- "2 19:00 180 0 Mareike Bautz"

ğŸ–ï¸ Strand:
- "1 16:00 180 0 Sandro Botsvadze"
- "1 19:00 180 0 Olsvanger"
- "2 08:00 120 0 *Techno Yoga*"
- "2 10:00 120 0 Dr. Long"
- "2 12:00 60 0 Gabunia *LIVE*"
- "2 13:00 180 0 9Eye"
- "2 16:00 180 0 Shir Khan"
- "2 19:00 180 0 Joyce Muniz"

ğŸ’ƒğŸ•º Wintergarten:
- "1 16:00 180 0 Reece Walker"
- "1 19:00 180 0 Bress Underground"
- "1 22:00 180 0 DJ Fett Burger"
- "2 01:00 180 0 Joj"
- "2 04:00 180 0 Vakho"
- "2 07:00 180 0 Boya"
- "2 10:00 180 0 Tomma"
- "2 13:00 180 0 Juli N More"
- "2 16:00 180 0 Hatsvali"
- "2 19:00 180 0 Ady Toledano"
- "2 22:00 240 0 Johannes Albert"
- "3 02:00 240 0 Mike Terra & Nat Wendell"
- "3 06:00 240 0 Norman Weber"

â›´ Dampfer:
- "1 21:00 180 0 Nicole"
- "2 00:00 90 0 Beqa *LIVE*"
- "2 01:30 210 0 Ikako"
- "2 05:00 180 0 Shakolin"
- "2 08:00 180 0 Sumo"
- "2 22:00 120 0 The Magic Touch *KONZERT*"

ğŸ”¨ Hammahalle:
- "1 22:00 180 0 Steven Shade" # 2024-08-10
- "2 01:00 180 0 Bullzeye" # 2024-08-11
- "2 04:00 180 0 Boyd Schidt" # 2024-08-11
- "2 07:00 180 0 Simo Lorenz" # 2024-08-11
- "2 22:00 210 0 Tutti" # 2024-08-11
- "3 01:30 270 0 Vas" # 2024-08-12
